# Generated by Django 4.2.2 on 2023-07-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0003_usergroup_alter_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='group',
            field=models.ManyToManyField(default=0, to='socialapp.usergroup'),
        ),
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ManyToManyField(default=0, to='socialapp.usergroup'),
        ),
    ]
