# Generated by Django 4.2.2 on 2023-06-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0003_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='faculty',
            field=models.IntegerField(choices=[(0, '工学部'), (1, '理学部')], default=0),
        ),
    ]
