# Generated by Django 4.2.2 on 2023-07-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0004_customuser_group_post_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='chattalk',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
