# Generated by Django 4.2.2 on 2023-06-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0004_alter_customuser_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='grade',
            field=models.IntegerField(choices=[(1, '1回生'), (2, '2回生'), (3, '3回生'), (4, '4回生'), (5, '5回生'), (6, '6回生'), (7, '修士1回生'), (8, '修士2回生'), (9, '博士1回生'), (10, '博士2回生')], default=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='faculty',
            field=models.IntegerField(choices=[(0, '総合人間学部'), (1, '文学部'), (2, '教育学部'), (3, '法学部'), (4, '経済学部'), (5, '理学部'), (6, '医学部医学科'), (7, '医学部人間健康科学科'), (8, '薬学部'), (9, '工学部'), (10, '農学部')], default=0),
        ),
    ]
