# Generated by Django 4.2.2 on 2023-06-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0005_customuser_grade_alter_customuser_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='faculty',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='grade',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='faculty',
            field=models.IntegerField(choices=[(1, '総合人間学部'), (2, '文学部'), (3, '教育学部'), (4, '法学部'), (5, '経済学部'), (6, '理学部'), (7, '医学部医学科'), (8, '医学部人間健康科学科'), (9, '薬学部'), (10, '工学部'), (11, '農学部')], default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='grade',
            field=models.IntegerField(choices=[(1, '1回生'), (2, '2回生'), (3, '3回生'), (4, '4回生'), (5, '5回生'), (6, '6回生')], default=1),
        ),
    ]
