# Generated by Django 4.2.2 on 2023-07-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0005_chattalk_is_read_alter_usergroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
