# Generated by Django 4.2.2 on 2023-06-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0006_question_faculty_question_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
