# Generated by Django 4.2.2 on 2023-06-25 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0007_customuser_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatMessage',
            new_name='ChatTalk',
        ),
        migrations.RenameField(
            model_name='chattalk',
            old_name='message',
            new_name='talk',
        ),
    ]
